# Generated by Django 3.1.2 on 2020-11-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201102_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(default='No text', max_length=1000),
        ),
    ]
